Cardapp.WebApp/Cardapp.WebApp/Controllers/EstabelecimentoController.cs
using FireSharp.Interfaces;
using FireSharp.Config;
using Microsoft.AspNetCore.Mvc;
using System;
using Cardapp.WebApp.Models;
using FireSharp.Response;
using Microsoft.AspNetCore.Http;
using Cardapp.WebApp.SessionHelper;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using System.IO;
using System.Text;
using Microsoft.Net.Http.Headers;
using System.Threading.Tasks;

namespace Cardapp.WebApp.Controllers
{
    public class EstabelecimentoController : Controller
    {
        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "wvg4O1GNPzXqpGK95uGjhVValAjRiLX4iIM3P6YK",
            BasePath = "https://cardapp-d8eba-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;

        Estabelecimento estab;
        List<Musica> lista;

        [HttpGet]
        public IActionResult Index()
        {
            GetSuggestions(out estab, out lista);
            if (estab == null)
            {
                TempData["Erro"] = "Faça o login para acessar o sistema!";
                return RedirectToAction("Login", "Home");
            }
            ViewBag.sugestoes = lista;
            return View(estab);
        }

        private void GetSuggestions(out Estabelecimento estab, out List<Musica> lista)
        {
            client = new FireSharp.FirebaseClient(config);

            estab = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");
            FirebaseResponse response = client.Get("/suggestMusic/");
            JObject json;
            lista = new List<Musica>();
            try
            {
                json = JObject.Parse(response.Body);
                foreach (var m in json)
                {
                    var musica = m.Value.ToObject<Musica>();
                    if (musica.EstabId == estab.CodigoEstabelecimento)
                    {
                        lista.Add(musica);
                    }
                }
            } catch (Exception)
            {
                Musica musica = new Musica
                {
                    MusicName = "Nenhuma música adicionada ainda!",
                    UserEmail = " ",
                    SuggestMusicId = "empty-list"
                };
                lista.Add(musica);
            }

        }

        [HttpGet]
        public IActionResult Avaliacoes()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("/rating/");
            JObject json = JObject.Parse(response.Body);
            var lista = new List<Avaliacao>();
            Estabelecimento estab = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");

            foreach (var a in json)
            {
                var avaliacao = a.Value.ToObject<Avaliacao>();
                if (avaliacao.EstabId == estab.CodigoEstabelecimento)
                {
                    lista.Add(avaliacao);
                }
            }
            ViewBag.avaliacoes = lista;
            return View();
        }

        [HttpGet]
        public IActionResult Sugestoes()
        {
            GetSuggestions(out estab, out lista);
            return View(lista);
        }

        [HttpGet]
        public IActionResult CadastroGerente()
        {
            var estabelecimento = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");

            if (estabelecimento == null)
            {
                return RedirectToAction("CadastroEstabelecimento");
            }
            return View();

        }

        [HttpPost]
        public IActionResult CadastroGerente(Gerente gerente)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    client = new FireSharp.FirebaseClient(config);
                    FirebaseResponse response = client.Get("/gerente/");
                    if (response.Body != "null")
                    {
                        JObject json = JObject.Parse(response.Body);

                        foreach (var i in json)
                        {
                            var gerenteReceived = i.Value.ToObject<Gerente>();
                            if (gerenteReceived.Email == gerente.Email)
                            {
                                TempData["Erro"] = "Erro ao cadastrar o gerente, esse email já foi cadastrado por outro gerente.";
                                return View();
                            }
                        }

                    }

                    var estabelecimento = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");
                    PushResponse responseEstab = client.Push("estab/", estabelecimento);
                    estabelecimento.CodigoEstabelecimento = responseEstab.Result.name;
                    SetResponse setResponseEstab = client.Set("estab/" + estabelecimento.CodigoEstabelecimento, estabelecimento);

                    Relatorio relatorio = new Relatorio
                    {
                        CodigoEstabelecimento = responseEstab.Result.name,
                    };
                    PushResponse responseRelatorio = client.Push("Relatorio/", relatorio);
                    relatorio.CodigoRelatorio = responseRelatorio.Result.name;
                    SetResponse setResponseRelatorio = client.Set("Relatorio/" + relatorio.CodigoRelatorio, relatorio);

                    var data = gerente;
                    gerente.CodigoEstabelecimento = estabelecimento.CodigoEstabelecimento;
                    PushResponse responseGerente = client.Push("gerente/", data);
                    data.CodigoGerente = responseGerente.Result.name;
                    SetResponse setResponseGerente = client.Set("gerente/" + data.CodigoGerente, data);

                    TempData["Sucesso"] = "Bem vindo(a) ao Cardapp!";


                    // Guardar estab na sessão novamente
                    HttpContext.Session.SetObjectAsJson("EstabelecimentoSessao", estabelecimento);
                    HttpContext.Session.SetObjectAsJson("GerenteSessao", gerente);
                    return RedirectToAction("index");

                }
                catch (Exception)
                {
                    TempData["Erro"] = "Erro ao cadastrar!";
                    return View();
                }
            }
            return View();
        }


        [HttpGet]
        public IActionResult EditarGerente()
        {
            if (HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao") == null)
            {
                TempData["Erro"] = "Faça o login para acessar o sistema!";
                return RedirectToAction("Login", "Home");
            }
            Gerente gerente = HttpContext.Session.GetObjectFromJson<Gerente>("GerenteSessao");

            return View(gerente);
        }

        [HttpPost]
        public IActionResult EditarGerente(Gerente gerente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    client = new FireSharp.FirebaseClient(config);
                    Gerente gerenteSessao = HttpContext.Session.GetObjectFromJson<Gerente>("GerenteSessao");

                    if (gerenteSessao.Email == gerente.Email && gerenteSessao.CodigoGerente != gerente.CodigoGerente)
                    {
                        TempData["Erro"] = "Erro ao editar o gerente, esse email já foi cadastrado por outro gerente.";
                        return View();
                    }
                    if (gerenteSessao.CodigoGerente == gerente.CodigoGerente)
                    {
                        string senha = Request.Form["senhaAtual"];
                        Console.WriteLine(senha);
                        if (senha != gerenteSessao.Senha)
                        {
                            TempData["Erro"] = "A senha informada está incorreta.";
                            return RedirectToAction("EditarGerente");
                        }
                        gerenteSessao.Senha = senha;
                    }
                    client.Update("/gerente/" + gerente.CodigoGerente, gerente);
                    HttpContext.Session.SetObjectAsJson("GerenteSessao", gerente);
                    TempData["Sucesso"] = "Alterações salvas com sucesso!";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception)
            {
                Console.WriteLine("Entrou no catch");
                TempData["Erro"] = "Não foi possível salvar as alterações!";
                return RedirectToAction("EditarGerente");
            }
        }

        [HttpGet]
        public IActionResult EditarSenha()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EditarSenha(string novaSenha)
        {
            try
            {
                client = new FireSharp.FirebaseClient(config);
                Gerente gerenteSessao = HttpContext.Session.GetObjectFromJson<Gerente>("GerenteSessao");

                string senha = Request.Form["senhaAtual"];
                if (senha != gerenteSessao.Senha)
                {
                    TempData["Erro"] = "A senha informada está incorreta.";
                    return RedirectToAction("EditarGerente");
                }
                gerenteSessao.Senha = novaSenha;
                Console.WriteLine(gerenteSessao.Senha);
                client.Update("/gerente/" + gerenteSessao.CodigoGerente, gerenteSessao);
                HttpContext.Session.SetObjectAsJson("GerenteSessao", gerenteSessao);
                TempData["Sucesso"] = "Alterações salvas com sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

Cardapp.WebApp/Cardapp.WebApp/Controllers/HomeController.cs
using Cardapp.WebApp.Models;
using Cardapp.WebApp.SessionHelper;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System;
using System.Diagnostics;
using System.Net;
using System.Net.Mail;

namespace Cardapp.WebApp.Controllers
{
    public class HomeController : Controller
    {

        public bool Logado { get; set; }

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "wvg4O1GNPzXqpGK95uGjhVValAjRiLX4iIM3P6YK",
            BasePath = "https://cardapp-d8eba-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Projeto()
        {
            return View();
        }

        public ActionResult Grupo()
        {
            return View();
        }
        
        public IActionResult Contato()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string senha)
        {
            client = new FireSharp.FirebaseClient(config);

            FirebaseResponse response = client.Get("/gerente/");
            JObject json = JObject.Parse(response.Body);

            foreach (var g in json)
            {
                //Console.WriteLine(g.Value.ToObject<Gerente>().NomeGerente);
                var gerente = g.Value.ToObject<Gerente>();
                if (gerente.Email == email && gerente.Senha == senha)
                {
                    if (ModelState.IsValid)
                    {
                        response = client.Get("/estab/");
                        json = JObject.Parse(response.Body);
                        foreach (var e in json)
                        {
                            var estab = e.Value.ToObject<Estabelecimento>();
                            if (gerente.CodigoEstabelecimento == estab.CodigoEstabelecimento)
                            {
                                HttpContext.Session.SetObjectAsJson("EstabelecimentoSessao", estab);
                                HttpContext.Session.SetObjectAsJson("GerenteSessao", gerente);
                                HttpContext.Session.SetString("NomeEstabelecimento", estab.NomeFantasia);
                                return RedirectToAction("Index", "Estabelecimento");
                            }
                        }
                    }
                }
            }

            TempData["Erro"] = "Login inválido! Verifique se o e-mail e senha estão corretos.";
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Cardapp.WebApp/Cardapp.WebApp/Controllers/TesteEmailController.cs
using Cardapp.WebApp.Models;
using Cardapp.WebApp.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Cardapp.WebApp.Controllers
{
    public class TesteEmailController : Controller
    {
        private readonly IEmailSender _emailSender;

        [Obsolete]
        public TesteEmailController(IEmailSender emailSender, IHostingEnvironment env)
        {
            _emailSender = emailSender;
        }
        public IActionResult EnviaEmail()
        {
            return View();
        }
        [HttpPost]
        public IActionResult EnviaEmail(Email email)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TesteEnvioEmail(email.EmailResposta, email.Nome, email.Assunto, email.Mensagem).GetAwaiter();
                    TempData["Sucesso"] = "E-mail enviado com sucesso!";
                }
                catch (Exception)
                {
                    TempData["Erro"] = "Algo deu errado... Tente novamente mais tarde!";
                }
            }
            return RedirectToAction("Contato", "home");
        }
        public async Task TesteEnvioEmail(string remetente, string nome, string assunto, string mensagem)
        {
            try
            {
                await _emailSender.SendEmailAsync(remetente, nome, assunto, mensagem);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Cardapp.WebApp/Cardapp.WebApp/Views/Home/CadastroGerente.cshtml
@model Gerente
@{ ViewData["Title"] = "Cadastro de gerente";
    Layout = "_LayoutNavSide";}



<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />

<div style="display: flex; flex-direction: column; justify-content: center; margin-left: 8%;">
    <h1 style="display: flex; justify-content: center;" class="my-5 text-white">Cadastre um gerente</h1>
    <div class="card cardStyle mx-auto" style="width: 70%">
        <form asp-action="Cadastrar">
            <div class="form-row">
                <label asp-for="NomeGerente"></label>
                <input asp-for="NomeGerente" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Salario"></label>
                <input asp-for="Salario" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Endereco"></label>
                <input asp-for="Endereco" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Senha"></label>
                <input asp-for="Senha" class="form-control">
            </div>

            <div class="form-row formRowStyleButton">
                <input type="submit" value="Salvar" class="btn btn-info mr-3 px-5" />
                <a asp-action="Index" class="btn btn-outline-danger px-5">Cancelar</a>
            </div>
        </form>
    </div>
</div>



<style>

    html {
        background-color: #4196A6;
    }
    .cardStyle {
        width: 90%;
        border: 2px solid #800;
        height: 80%;
        padding: 2%;
    }

    .formRowStyleButton {
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        margin-top: 3vh;
    }
</style>

Cardapp.WebApp/Cardapp.WebApp/Views/Home/CadastroRestaurante.cshtml
@model Estabelecimento
@{ ViewData["Title"] = "Cadastro de restaurante";
    Layout = "_LayoutNavSide";}



<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />

<div style="display: flex; flex-direction: column; justify-content: center; margin-left: 8%;">
    <h1 style="display: flex; justify-content: center;" class="my-5 text-white">Cadastre um restaurante</h1>
    <div class="card cardStyle mx-auto" style="width: 70%">
        <form asp-action="Cadastrar">
            <div class="form-row">
                <label asp-for="RazaoSocial"></label>
                <input asp-for="RazaoSocial" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="NomeFantasia"></label>
                <input asp-for="NomeFantasia" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Cnpj"></label>
                <input asp-for="Cnpj" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Endereco"></label>
                <input asp-for="Endereco" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Telefone"></label>
                <input asp-for="Telefone" class="form-control">
            </div>
            <div class="form-row">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control">
            </div>
            <div class="form-row formRowStyleButton">
                <input type="submit" value="Salvar" class="btn btn-info mr-3 px-5" />
                <a asp-action="Index" class="btn btn-outline-danger px-5">Cancelar</a>
            </div>
        </form>
    </div>
</div>



<style>

    html {
        background-color: #4196A6;
    }

    .cardStyle {
        width: 90%;
        border: 2px solid #800;
        height: 80%;
        padding: 2%;
    }

    .formRowStyleButton {
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        margin-top: 3vh;
    }
</style>

Cardapp.WebApp/Cardapp.WebApp/Views/Home/Contato.cshtml
@model Email
@{
    ViewData["Title"] = "Contato";
    Layout = "_LayoutNavSide";
}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/buttons.css" rel="stylesheet" />

<div class="right-content" style="display: flex; flex-direction: column; margin-right: 10%; width: 70%">
    <div class="card mt-5 mb-5 border-danger" style="border-radius: 15px">
        @if (@TempData["Sucesso"] != null)
        {
            <Feedback Texto="@TempData["Sucesso"]" is-error="false"></Feedback>
        }
        else
        {
            <Feedback Texto="@TempData["Erro"]" is-error="true"></Feedback>
        }

        <div style="display: flex; flex-direction: column; align-items: center">
            <h3 class="mt-5 mb-4">Mande um e-mail para nós!</h3>

            <form asp-action="EnviaEmail" asp-controller="TesteEmail" style="width: 80%; min-height: 50vh">
                <div class="form-group">
                    <label asp-for="EmailResposta"></label>
                    <input asp-for="EmailResposta" class="form-control" />
                    <span asp-validation-for="EmailResposta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nome"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Assunto"></label>
                    <input asp-for="Assunto" class="form-control" />
                    <span asp-validation-for="Assunto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mensagem"></label>
                    <textarea asp-for="Mensagem" class="form-control"></textarea>
                    <span asp-validation-for="Mensagem" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-success mb-5">Enviar</button>
            </form>
        </div>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Home/Grupo.cshtml
@{
    ViewData["Title"] = "Sobre Nós";
    Layout = "_Layout";
}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Wendy+One&display=swap" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/index-about.css" rel="stylesheet" />

<div class="page-content">
    <partial name="_LeftContent" />
    <div class="right-content mb-5">
        <div>
            <div>
                <p class="page-title">Sobre Nós</p>
            </div>
            <div class="d-flex align-items-center justify-content-around">
                <p class="paragraph" style="width: 40%;">
                    Um recomeço. Novas descobertas, infinitas possibilidades e vontade de fazer bonito e com a melhor qualidade,
                    independente do prazo. Então nos encontramos, nos unimos e demos início ao longo processo do conhecimento.
                </p>
                <img src="~/img/group-work.svg" class="main-image" width="600" />
            </div>
        </div>
        <div>
            <div class="d-flex align-items-center justify-content-around">
                <img src="~/img/meeting.svg" class="main-image" width="600" />
                <p class="paragraph" style="width: 40%;">
                    Com muita dedicação, conquistamos em 2020 o prêmio DISRUPT 21, algo que trouxe muito conhecimento e experiencia para todos os membros de nosso grupo.
                    Um dos pontos fortes de nossa equipe, cada membro tem habilidades em setores diferentes, o que nos torna eficientes e produtivos em uma rotina de entregas e trabalhos.
                </p>
            </div>
        </div>
        <div>
            <div class="d-flex align-items-center justify-content-around">
                <p class="paragraph" style="width: 40%;">
                    Conquistamos não apenas prêmios, mas também uma amizade que transcende estudos e trabalhos. E é claro, que se estamos em um ambiente confortável e prazeroso, conseguimos desenvolver mais e criar ideias incríveis.
                </p>
                <img src="~/img/team.svg" class="main-image" width="600" />
            </div>
        </div>
        <div class="d-flex flex-column align-items-center mb-5 func-disp">
            <p class="paragraph">Conheça um pouco sobre os membros da nossa equipe</p>
            <img src="~/img/arrowDown.png" width="100" />
        </div>

        <div class="container">
            <!-- Example row of columns -->
            <div class="row">
                <div class="col-md-4">
                    <img alt="ftKaue" src="~/img/poagilers/kaue.png">
                    <h2>Kaue Augusto</h2>
                    <p>RM 85707</p>
                </div>

                <div class="col-md-4">
                    <img alt="ftLari" src="~/img/poagilers/larissa.png">
                    <h2>Larissa Alves</h2>
                    <p>RM 86351</p>
                </div>

                <div class="col-md-4">
                    <img alt="ftDan" src="~/img/poagilers/daniel.png">
                    <h2>Daniel Sanchez</h2>
                    <p>RM 85109</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-4">
                    <img alt="ftDan" src="~/img/poagilers/henrique.png">
                    <h2>Henrique Neves</h2>
                    <p>RM 84549</p>
                </div>

                <div class="col-md-4">
                    <img alt="ftGi" src="~/img/poagilers/gi.png">
                    <h2>Giovanna de Mello</h2>
                    <p>RM 85817</p>
                </div>

                <div class="col-md-4">
                    <img alt="ftEric" src="~/img/poagilers/eric.png">
                    <h2>Eric Luiz</h2>
                    <p>RM 86405</p>
                </div>
            </div>

            <hr>
        </div>

        <footer class="mt-4 col-11 d-flex justify-content-center align-content-center">
            <p>&copy; Poagilers Company</p>
        </footer>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Cardapp";
}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Wendy+One&display=swap" rel="stylesheet">
<link href="~/css/index-home.css" rel="stylesheet" />

<style>
    html {
        background-color: #B56357;
    }

    body {
        background: linear-gradient(180deg, #B56357, #EAE3EA);
    }
</style>

<div class="text-center d-flex justify-content-around">
    <div class="d-flex flex-column" style="width: 30%">
        <div class="d-flex flex-column left-content">
            <a class="navbar-brand d-flex justify-content-lg-start mt-3" asp-controller="Home" asp-action="Index">
                <img src="~/img/logo.svg" class="logo" />
            </a>
        </div>
        <div>
            <div class="d-flex justify-content-end" style="margin-top: 50px">
                <h3 class="text-left index-title">Uma nova forma de aproveitar as refeições</h3>
            </div>
        </div>
    </div>
    <div style="margin-top: 50px;" class="d-flex flex-column align-items-end">
        <img src="~/img/dinner.svg" class="index-image" />
        <a asp-action="projeto" style="margin-top: -10%;" title="Sobre o projeto" >
            <img src="/img/next.svg" class="animated-button" />
        </a>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Home/Login.cshtml
@model Gerente
@{
    ViewData["Title"] = "Login";
}

<link href="https://fonts.googleapis.com/css2?family=Wendy+One&display=swap" rel="stylesheet">
<link href="~/css/index-about.css" rel="stylesheet" />
<link href="~/css/master.css" rel="stylesheet" />

<div class="page-content">
    <partial name="_LeftContent" />
    <div>
        <div class="d-flex justify-content-center right-content">
            <div class="text-center" style="background-color: #fffa; box-shadow: 6px 6px 10px #333; width: 60%; margin: 5% 0; border-radius: 15px; border: 1px #800 solid; padding: 2%;">
                <feedback texto="@TempData["Erro"]" is-error="true"></feedback>
                <h2 style="color: #555; margin-bottom: 2%">Login</h2>
                <form asp-action="Login" style="padding-left: 15%; padding-right: 15% ">
                    <label for="id-email">E-mail</label>
                    <input id="id-email" asp-for="NomeGerente" name="email" class="form-control" />

                    <label for="id-senha">Senha</label>
                    <input id="id-senha" asp-for="Senha" name="senha" class="form-control" />

                    <input type="submit" value="Entrar" class="btn btn-info" style="margin-top: 5%; margin-bottom: 5%;" />
                </form>
                <a asp-action="CadastroEstabelecimento" asp-controller="Estabelecimento">Não possui conta? Cadastre-se clicando aqui!</a>
            </div>
        </div>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Home/_LeftContent.cshtml
<script src="myscripts.js"></script>

<div class="d-flex flex-column justify-content-between align-items-center left-content">
    <a class="mt-3" asp-area="" asp-controller="Home" asp-action="Index">
        <img src="~/img/logo.svg" width="100" />
    </a>
    <div class="text-white d-flex justify-content-center">
        <p class="menu-title">Conheça nossos recursos exclusivos</p>
    </div>
    <div class="d-flex flex-column">
        <a class="btn btn-info btn-lg mb-4 menu-button" role="button" asp-action="projeto">Sobre o projeto </a>
        <a class="btn btn-info btn-lg mb-4 menu-button" role="button" asp-action="grupo">Sobre nós</a>
        <a class="btn btn-info btn-lg mb-4 menu-button" role="button" asp-action="contato">Contato</a>
        <a class="btn btn-primary btn-lg mb-4 menu-button" asp-action="Login" asp-controller="Home" role="button">Login</a>
        <a class="btn btn-primary btn-lg menu-button" asp-action="CadastroEstabelecimento" asp-controller="Estabelecimento" role="button">Cadastro</a>

    </div>
    <button onclick="goBack()" class="mb-3 btn" style="-moz-transform: scaleX(-1); -o-transform: scaleX(-1); -webkit-transform: scaleX(-1); transform: scaleX(-1);">
        <img src="/img/next.svg" class="animated-button" />
    </button>
</div>