Cardapp.WebApp/Cardapp.WebApp/Models/Estabelecimento.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cardapp.WebApp.Models
{

    [Table("T_CPP_ESTABELECIMENTO")]
    public class Estabelecimento
    {
        [Key]
        [Column("CD_ESTABELECIMENTO")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [HiddenInput]
        public string CodigoEstabelecimento { get; set; }

        [Column("NM_RAZAO_SOCIAL")]
        [Display(Name = "Qual a razão social do seu estabelecimento?")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [MinLength(5, ErrorMessage = "A razão social deve ter 5 caracteres ou mais.")]
        [MaxLength(50, ErrorMessage = "A razão social deve ter menos de 50 caracteres")]
        public string RazaoSocial { get; set; }


        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [Column("NM_FANTASIA")]
        [Display(Name = "Qual o nome fantasia do seu estabelecimento?")]
        [MinLength(2, ErrorMessage = "O nome fantasia deve ter 2 caracteres ou mais.")]
        [MaxLength(50, ErrorMessage = "O nome fantasia deve ter menos de 50 caracteres")]
        public string NomeFantasia { get; set; }

        [RegularExpression(@"[0-9]{2}\.?[0-9]{3}\.?[0-9]{3}\/?[0-9]{4}\-?[0-9]{2}", ErrorMessage = "O cnpj deve ter 14 caracteres sem pontuação. Exemplo: 12345678912345")]
        [Column("DS_CNPJ")]
        [Display(Name = "Cnpj do estabelecimento")]
        [MaxLength(14, ErrorMessage = "O cnpj deve ter 14 caracteres sem pontuação.")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        public string Cnpj { get; set; }

        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [Column("DS_ENDERECO")]
        [Display(Name = "Qual o endereço do seu estabelecimento?")]
        [MinLength(10, ErrorMessage = "O campo de endereço deve ter 10 caracteres ou mais.")]
        [MaxLength(100, ErrorMessage = "O endereço deve ter menos de 100 caracteres")]
        public string Endereco { get; set; }

        [RegularExpression(@"(^[0-9]{2})([9]{1})?([0-9]{8})", ErrorMessage = "O telefone deve ter 11 caracteres sem pontuação (ddd + número). Ex: 11912345678.")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [Column("NR_TELEFONE")]
        [Display(Name = "Qual o telefone do seu estabelecimento?")]
        [MaxLength(11, ErrorMessage = "O telefone deve ter exatamente 11 caracteres")]
        public string Telefone { get; set; }

        [EmailAddress]
        [MaxLength(40, ErrorMessage = "O email deve ter menos de 40 caracteres")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [Column("DS_EMAIL")]
        [Display(Name = "Qual o email do seu estabelecimento?")]
        public string Email { get; set; }
    }
}

Cardapp.WebApp/Cardapp.WebApp/Models/Relatorio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Cardapp.WebApp.Models
{
    public class Relatorio
    {
        public string CodigoRelatorio { get; set; }

        public string CodigoEstabelecimento { get; set; }

        public int NumeroAcessosTotal { get; set; }

        public int NumeroAcessosItemCardapio { get; set; }

        public int NumeroAtivacaoLuz { get; set; }

    }
}

Cardapp.WebApp/Cardapp.WebApp/Controllers/EstabelecimentoController.cs
using FireSharp.Interfaces;
using FireSharp.Config;
using Microsoft.AspNetCore.Mvc;
using System;
using Cardapp.WebApp.Models;
using FireSharp.Response;
using Microsoft.AspNetCore.Http;
using Cardapp.WebApp.SessionHelper;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using System.IO;
using System.Text;
using Microsoft.Net.Http.Headers;
using System.Threading.Tasks;

namespace Cardapp.WebApp.Controllers
{
    public class EstabelecimentoController : Controller
    {
        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "wvg4O1GNPzXqpGK95uGjhVValAjRiLX4iIM3P6YK",
            BasePath = "https://cardapp-d8eba-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;

        Estabelecimento estab;
        List<Musica> lista;

        [HttpGet]
        public IActionResult Index()
        {
            GetSuggestions(out estab, out lista);
            if (estab == null)
            {
                TempData["Erro"] = "Faça o login para acessar o sistema!";
                return RedirectToAction("Login", "Home");
            }
            ViewBag.sugestoes = lista;
            return View(estab);
        }

        private void GetSuggestions(out Estabelecimento estab, out List<Musica> lista)
        {
            client = new FireSharp.FirebaseClient(config);

            estab = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");
            FirebaseResponse response = client.Get("/suggestMusic/");
            JObject json;
            lista = new List<Musica>();
            try
            {
                json = JObject.Parse(response.Body);
                foreach (var m in json)
                {
                    var musica = m.Value.ToObject<Musica>();
                    if (musica.EstabId == estab.CodigoEstabelecimento)
                    {
                        lista.Add(musica);
                    }
                }
            } catch (Exception)
            {
                Musica musica = new Musica
                {
                    MusicName = "Nenhuma música adicionada ainda!",
                    UserEmail = " ",
                    SuggestMusicId = "empty-list"
                };
                lista.Add(musica);
            }

        }

        [HttpGet]
        public IActionResult Avaliacoes()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("/rating/");
            JObject json = JObject.Parse(response.Body);
            var lista = new List<Avaliacao>();
            Estabelecimento estab = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");

            foreach (var a in json)
            {
                var avaliacao = a.Value.ToObject<Avaliacao>();
                if (avaliacao.EstabId == estab.CodigoEstabelecimento)
                {
                    lista.Add(avaliacao);
                }
            }
            ViewBag.avaliacoes = lista;
            return View();
        }

        [HttpGet]
        public IActionResult Sugestoes()
        {
            GetSuggestions(out estab, out lista);
            return View(lista);
        }

        [HttpGet]
        public IActionResult CadastroGerente()
        {
            var estabelecimento = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");

            if (estabelecimento == null)
            {
                return RedirectToAction("CadastroEstabelecimento");
            }
            return View();

        }

        [HttpPost]
        public IActionResult CadastroGerente(Gerente gerente)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    client = new FireSharp.FirebaseClient(config);
                    FirebaseResponse response = client.Get("/gerente/");
                    if (response.Body != "null")
                    {
                        JObject json = JObject.Parse(response.Body);

                        foreach (var i in json)
                        {
                            var gerenteReceived = i.Value.ToObject<Gerente>();
                            if (gerenteReceived.Email == gerente.Email)
                            {
                                TempData["Erro"] = "Erro ao cadastrar o gerente, esse email já foi cadastrado por outro gerente.";
                                return View();
                            }
                        }

                    }

                    var estabelecimento = HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao");
                    PushResponse responseEstab = client.Push("estab/", estabelecimento);
                    estabelecimento.CodigoEstabelecimento = responseEstab.Result.name;
                    SetResponse setResponseEstab = client.Set("estab/" + estabelecimento.CodigoEstabelecimento, estabelecimento);

                    Relatorio relatorio = new Relatorio
                    {
                        CodigoEstabelecimento = responseEstab.Result.name,
                    };
                    PushResponse responseRelatorio = client.Push("Relatorio/", relatorio);
                    relatorio.CodigoRelatorio = responseRelatorio.Result.name;
                    SetResponse setResponseRelatorio = client.Set("Relatorio/" + relatorio.CodigoRelatorio, relatorio);

                    var data = gerente;
                    gerente.CodigoEstabelecimento = estabelecimento.CodigoEstabelecimento;
                    PushResponse responseGerente = client.Push("gerente/", data);
                    data.CodigoGerente = responseGerente.Result.name;
                    SetResponse setResponseGerente = client.Set("gerente/" + data.CodigoGerente, data);

                    TempData["Sucesso"] = "Bem vindo(a) ao Cardapp!";


                    // Guardar estab na sessão novamente
                    HttpContext.Session.SetObjectAsJson("EstabelecimentoSessao", estabelecimento);
                    HttpContext.Session.SetObjectAsJson("GerenteSessao", gerente);
                    return RedirectToAction("index");

                }
                catch (Exception)
                {
                    TempData["Erro"] = "Erro ao cadastrar!";
                    return View();
                }
            }
            return View();
        }


        [HttpGet]
        public IActionResult EditarGerente()
        {
            if (HttpContext.Session.GetObjectFromJson<Estabelecimento>("EstabelecimentoSessao") == null)
            {
                TempData["Erro"] = "Faça o login para acessar o sistema!";
                return RedirectToAction("Login", "Home");
            }
            Gerente gerente = HttpContext.Session.GetObjectFromJson<Gerente>("GerenteSessao");

            return View(gerente);
        }

        [HttpPost]
        public IActionResult EditarGerente(Gerente gerente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    client = new FireSharp.FirebaseClient(config);
                    Gerente gerenteSessao = HttpContext.Session.GetObjectFromJson<Gerente>("GerenteSessao");

                    if (gerenteSessao.Email == gerente.Email && gerenteSessao.CodigoGerente != gerente.CodigoGerente)
                    {
                        TempData["Erro"] = "Erro ao editar o gerente, esse email já foi cadastrado por outro gerente.";
                        return View();
                    }
                    if (gerenteSessao.CodigoGerente == gerente.CodigoGerente)
                    {
                        string senha = Request.Form["senhaAtual"];
                        Console.WriteLine(senha);
                        if (senha != gerenteSessao.Senha)
                        {
                            TempData["Erro"] = "A senha informada está incorreta.";
                            return RedirectToAction("EditarGerente");
                        }
                        gerenteSessao.Senha = senha;
                    }
                    client.Update("/gerente/" + gerente.CodigoGerente, gerente);
                    HttpContext.Session.SetObjectAsJson("GerenteSessao", gerente);
                    TempData["Sucesso"] = "Alterações salvas com sucesso!";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception)
            {
                Console.WriteLine("Entrou no catch");
                TempData["Erro"] = "Não foi possível salvar as alterações!";
                return RedirectToAction("EditarGerente");
            }
        }

        [HttpGet]
        public IActionResult EditarSenha()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EditarSenha(string novaSenha)
        {
            try
            {
                client = new FireSharp.FirebaseClient(config);
                Gerente gerenteSessao = HttpContext.Session.GetObjectFromJson<Gerente>("GerenteSessao");

                string senha = Request.Form["senhaAtual"];
                if (senha != gerenteSessao.Senha)
                {
                    TempData["Erro"] = "A senha informada está incorreta.";
                    return RedirectToAction("EditarGerente");
                }
                gerenteSessao.Senha = novaSenha;
                Console.WriteLine(gerenteSessao.Senha);
                client.Update("/gerente/" + gerenteSessao.CodigoGerente, gerenteSessao);
                HttpContext.Session.SetObjectAsJson("GerenteSessao", gerenteSessao);
                TempData["Sucesso"] = "Alterações salvas com sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

Cardapp.WebApp/Cardapp.WebApp/Views/Estabelecimento/Avaliacoes.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@model Avaliacao

@{
    ViewData["Title"] = "Avaliações";
    Layout = "_LayoutNavSide";
}

<partial name="_BotoesSessao" />

<div style="display: flex; flex-direction: column; min-width: 90%;" class="right-content mb-5">
    <h2 style="display: flex; justify-content: center;" class="mb-5 mt-3">Avaliações - @HttpContextAccessor.HttpContext.Session.GetString("NomeEstabelecimento")</h2>

    <div class="d-flex align-self-end border-danger" style="flex-wrap: wrap; min-width: 85%; margin-left: 10%">
            @foreach (var a in ViewBag.avaliacoes)
            {
                <div class="card d-flex flex-column col-3 border-danger" style="padding: 4%; margin: 1%; border-radius: 15px; box-shadow: 5px 4px 12px #333">
                    <div>
                        <h5>Avaliação de @a.UserName</h5>
                        <p>E-mail: @a.UserEmail</p>
                    </div>
                    <p style="font-size: 1.5rem" class="text-center">@a.Rating <span class="material-icons text-warning mt-2">star</span></p>
                    <div class="d-flex">
                        <b class="mr-2">Avaliação: </b>
                        <p>@(a.Text != "" ? a.Text : "-------")</p>
                    </div>
                </div>
            }
        @if (ViewBag.avaliacoes.Count == 0)
        {
            <h5 class="text-info">Nenhuma avaliação foi feita para o seu estabelecimento... ainda!</h5>
        }
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Estabelecimento/CadastroEstabelecimento.cshtml
@model Estabelecimento
@{
    ViewData["Title"] = "Cadastro de restaurante";
}


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Wendy+One&display=swap" rel="stylesheet">

<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/form-card.css" rel="stylesheet" />
<link href="~/css/index-about.css" rel="stylesheet" />

<div class="page-content">
    <partial name="_LeftContent" />
    <div class="right-content" style="display: flex; flex-direction: column; justify-content: center; margin-left: 8%;">
        <Feedback Texto="@TempData["Erro"]" is-error="true"></Feedback>
        <h1 style="display: flex; justify-content: center;" class="my-5">Cadastre um estabelecimento</h1>
        <div class="card cardStyle mx-auto" style="width: 70%; box-shadow: 6px 6px 10px #333;">
            <form asp-action="CadastroEstabelecimento">
                <partial name="_FormCreateUpdateEstabelecimento" />

                <div class="form-row formRowStyleButton">
                    <a asp-action="Projeto" asp-controller="home" class="btn btn-danger px-5">Cancelar</a>
                    <input type="submit" value="Próxima etapa" class="btn btn-info ml-3 px-5" />
                </div>
            </form>
        </div>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Estabelecimento/CadastroGerente.cshtml
@model Gerente

@{
    ViewData["Title"] = "Cadastro de gerente";
}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Wendy+One&display=swap" rel="stylesheet">

<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/form-card.css" rel="stylesheet" />
<link href="~/css/index-about.css" rel="stylesheet" />

<div class="page-content">
    <partial name="_LeftContent" />
    <div class="right-content" style="display: flex; flex-direction: column; justify-content: center; margin-left: 8%;">
        <Feedback Texto="@TempData["Erro"]" is-error="true"></Feedback>
        <h1 style="display: flex; justify-content: center;" class="my-5">Cadastre um gerente</h1>
        <div class="card cardStyle mx-auto" style="width: 70%; box-shadow: 6px 6px 10px #333;">
            <form asp-action="CadastroGerente">
                <partial name="_FormCreateUpdateGerente" />
                <div class="form-row justify-content-center mx-auto my-3" style="width: 96%;">
                    <label asp-for="Senha"></label>
                    <input asp-for="Senha" class="form-control">
                    <span asp-validation-for="Senha" class="text-danger mb-3" style="text-align: center"></span>
                </div>

                <div class="form-row formRowStyleButton">
                    <a asp-action="CadastroEstabelecimento" asp-controller="Estabelecimento" class="btn btn-danger px-5">Voltar</a>
                    <input type="submit" value="Salvar" class="btn btn-info ml-3 px-5" />
                </div>
            </form>
        </div>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Estabelecimento/EditarEstabelecimento.cshtml
@model Estabelecimento

@{
    ViewData["Title"] = "Editar Estabelecimento";
    Layout = "_LayoutNavSide";
}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/form-card.css" rel="stylesheet" />


<div style="display: flex; flex-direction: column; justify-content: center; margin-left: 8%;">
    <h1 style="display: flex; justify-content: center;" class="my-5">Edite as informações do estabelecimento</h1>
    <div class="card cardStyle mx-auto" style="width: 70%; padding: 3%; box-shadow: 6px 6px 10px #333;">
        <Feedback Texto="@TempData["Erro"]" is-error="true"></Feedback>
        <form asp-action="EditarEstabelecimento">
            <input asp-for="CodigoEstabelecimento" type="hidden" />
            <partial name="_FormCreateUpdateEstabelecimento" />

            <div class="form-row formRowStyleButton">
                <a asp-action="Index" class="btn btn-danger px-5">Voltar</a>
                <input type="submit" value="Salvar alterações" class="btn btn-info ml-3 px-5" />
            </div>
        </form>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Estabelecimento/EditarGerente.cshtml
@model Gerente

@{
    ViewData["Title"] = "Editar Gerente";
    Layout = "_LayoutNavSide";
}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/form-card.css" rel="stylesheet" />

<div style="display: flex; flex-direction: column; justify-content: center; margin-left: 8%;">
    <h1 style="display: flex; justify-content: center;" class="my-5">Edite suas informações</h1>
    <div class="card cardStyle mx-auto" style="width: 70%; padding: 3%; box-shadow: 6px 6px 10px #333;">
        <Feedback Texto="@TempData["Erro"]" is-error="true"></Feedback>
        <div class="d-flex justify-content-center">
            <a asp-action="EditarSenha" class="btn btn-outline-danger mb-4">Editar senha</a>
        </div>
        <form asp-action="EditarGerente">
            <input asp-for="CodigoGerente" type="hidden" />
            <input asp-for="Senha" type="hidden" />
            <partial name="_FormCreateUpdateGerente" />

            <div class="d-flex">
                <div class="form-row justify-content-center mx-auto my-3 col-6" style="width: 96%;">
                    <label for="id-senha">Senha atual</label>
                    <input for="id-senha" name="senhaAtual" class="form-control" autocomplete="off">
                </div>
            </div>

            <div class="form-row formRowStyleButton">
                <a asp-action="Index" class="btn btn-danger px-5">Voltar</a>
                <input type="submit" value="Salvar alterações" class="btn btn-info ml-3 px-5" />
            </div>
        </form>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Estabelecimento/Index.cshtml
@model Estabelecimento

@{
    ViewData["Title"] = "Gerenciar Conta";
    Layout = "_LayoutNavSide";
}
<style>
    .no-border:focus {
        outline: none;
        box-shadow: none;
    }

    .no-border:hover {
        color: #555
    }
</style>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/buttons.css" rel="stylesheet" />
<link href="~/css/indexEstabelecimento.css" rel="stylesheet" />

<meta http-equiv="refresh" content="60" />

<div class="mr-5 mt-5 d-flex justify-content-end">
    <a class="btn btn-danger btn-lg menu-button ml-2" role="button" style="box-shadow: 6px 6px 10px #333; padding-left: 20px" asp-action="Logout" asp-controller="Home">
        <span class="material-icons text-light">logout</span>
    </a>
</div>
<div class="dropdown mx-5 my-2 dropleft d-flex justify-content-end">
    <button class="btn btn-warning dropdown-toggle no-border" type="button" style="box-shadow: 6px 6px 10px #333;" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="material-icons no-border">notifications</span>
        @if (ViewBag.sugestoes.Count > 0 && ViewBag.sugestoes[0].SuggestMusicId != "empty-list")
        {
            <span class="text-danger" style="font-weight: bold">@ViewBag.sugestoes.Count</span>
        }
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <h5 style="margin: 20px;">Sugestões de músicas</h5>
        @if (ViewBag.sugestoes.Count <= 9)
        {
            @foreach (var m in ViewBag.sugestoes)
            {
                <div class="dropdown-item d-flex justify-content-between">
                    <p class="text-center mt-2">@m.MusicName - @m.ArtistName</p>
                    @if (m.SuggestMusicId != "empty-list")
                    {
                        <form asp-action="ApagarNotificacao">
                            <input name="id" type="hidden" value="@m.SuggestMusicId" />
                            <button type="submit" class="btn"><span class="material-icons ml-2 text-danger">delete_outline</span></button>
                        </form>
                    }
                </div>
            }
        }
        @if (ViewBag.sugestoes.Count > 0)
        {
            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-center text-info" asp-action="Sugestoes">Ver todas</a>
        }
        @if (ViewBag.sugestoes.Count == 0)
        {
            <p class="text-info mx-2">Nenhuma sugestão por enquanto</p>
        }
    </div>
</div>

<div style="display: flex; flex-direction: column; margin-top: 3%; margin-left: 7%; min-height: 80vh">
    <div class="card mx-auto" style="width: 70%; height: 70%; border-radius: 20px; box-shadow: 6px 6px 15px #333; ">
        @if (@TempData["Sucesso"] != null)
        {
            <Feedback Texto="@TempData["Sucesso"]" is-error="false"></Feedback>
        }
        else
        {
            <Feedback Texto="@TempData["Erro"]" is-error="true"></Feedback>
        }
        <row class="mt-4">
            <div class="d-flex row my-auto justify-content-around align-content-center">
                <div class="col-md-5 div-warning">
                    <span style="display: flex; justify-content: center; font-size: 40px; color: #FFc107" class="material-icons ml-2 mb-1">manage_accounts</span>
                    <h2 style="display: flex; justify-content: center;" class="mb-5 bold">Gerenciar Conta</h2>

                    <h3 style="display: flex; justify-content: center;" class="mb-3">Editar informações</h3>
                    <div class="mx-auto row justify-content-center">
                        <a asp-action="EditarGerente" asp-controller="Estabelecimento" class="btn btn-warning mx-2">Gerente</a>
                        <a asp-action="EditarEstabelecimento" asp-controller="Estabelecimento" class="btn btn-warning mx-2">Estabelecimento</a>
                    </div>
                </div>
                <div class="col-md-5 div-danger">
                    <h2 style="display: flex; justify-content: center;" class="mb-3 bold"><span class="material-icons text-danger" style="font-size: 50px">report_gmailerrorred</span></h2>

                    <h3 style="display: flex; justify-content: center;" class="mb-3">Apagar estabelecimento</h3>
                    <div class="mx-auto row justify-content-center">
                        <button type="button" class="mb-3 btn btn-danger" data-toggle="modal" data-target="#modalConfirma">
                            Apagar definitivamente
                        </button>
                    </div>
                </div>
            </div>
        </row>
        <row class="justify-content-center d-flex">
            <div class="mt-4 d-flex justify-content-around">
                <a asp-action="Index" asp-controller="ItemCardapio" class="btn botao mb-4 mx-2">Visualizar o cardápio</a>
                <a asp-action="Avaliacoes" asp-controller="Estabelecimento" class="btn botao mb-4 mx-2">Visualizar avaliações</a>
                <a asp-action="Relatorio" asp-controller="Estabelecimento" class="btn botao mb-4 mx-2">Relatório de interação</a>
            </div>
        </row>
    </div>
</div>



<div class="modal fade" id="modalConfirma" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #23272B; color: white">
                <h5 class="modal-title" id="modalLabel">Confirmação</h5>
            </div>
            <div class="modal-body" style="background-color: powderblue">
                <p>Não será possível reverter esta ação. Você não poderá mais acessar o sistema, seus dados, os do estabelecimento e todos os itens do cardápio serão apagados. Tem certeza que deseja apagar <b>definitivamente</b> o estabelecimento? </p>
            </div>
            <div class="modal-footer border-top-0" style="background-color: powderblue; color: white">
                <form asp-action="Remover">
                    <button type="button" class="btn btn-dark" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim, apagar estabelecimento</button>
                </form>
            </div>
        </div>
    </div>
</div>

Cardapp.WebApp/Cardapp.WebApp/Views/Estabelecimento/Relatorio.cshtml
@model Relatorio

@{
    ViewData["Title"] = "Relatório";
    Layout = "_LayoutNavSide";
}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="~/css/master.css" rel="stylesheet" />
<link href="~/css/buttons.css" rel="stylesheet" />


<div style="display: flex; flex-direction: column; justify-content: center; margin-left: 7%; min-height: 80vh">
    <div class="card mx-auto" style="width: 70%; height: 70%; border-radius: 20px; box-shadow: 6px 6px 15px #333; ">
        <row class="my-4 mx-auto justify-content-center">
            <h1 class="mb-5">Relatório de dados do estabelecimento</h1>
            <p class="h4">Número total de acessos: @Model.NumeroAcessosTotal</p>
            <p class="h4 mt-3">Número total de acesso a itens do cardápio: @Model.NumeroAcessosItemCardapio</p>
            <p class="h4 mt-3">Número de vezes que a função de iluminação da mesa foi utilizada: @Model.NumeroAtivacaoLuz</p>
            <a class="btn btn-lg btn-dark mt-5" asp-action="DownloadTxt" asp-controller="Estabelecimento">Baixe esse relatório</a>
        </row>
    </div>
</div>